version: '3'
services:
  app:
    container_name: node_app
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db/postgres
    depends_on:
      - db
  db:
    container_name: postgres_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
